const reasons = [
  "Kocham Cię za Twój uśmiech",
  "Kocham Cię za to, jak troszczysz się o mnie",
  "Kocham Cię za każdą rozmowę, która poprawia mi humor",
  "Kocham Cię za Twoją cierpliwość i zrozumienie",
  "Kocham Cię za Twoją energię, którą dzielisz ze mną",
  "Kocham Cię za każdą chwilę, którą spędzamy razem",
  "Kocham Cię za to, że potrafisz mnie rozśmieszyć w trudnych momentach",
  "Kocham Cię za to, jak dbasz o naszą przyszłość",
  "Kocham Cię za to, jak czujesz mnie bez słów",
  "Kocham Cię za Twój sposób bycia, który jest niepowtarzalny",
  "Kocham Cię za to, że przy Tobie czuję się bezpiecznie",
  "Kocham Cię za Twój niezwykły sposób patrzenia na świat",
  "Kocham Cię za to, że sprawiasz, że czuję się wyjątkowo",
  "Kocham Cię za to, że potrafisz słuchać i rozumieć",
  "Kocham Cię za Twoją mądrość",
  "Kocham Cię za Twoją wrażliwość",
  "Kocham Cię za to, jak mnie wspierasz w trudnych chwilach",
  "Kocham Cię za Twoje poczucie humoru",
  "Kocham Cię za to, że potrafisz mnie uspokoić",
  "Kocham Cię za Twoje niezłomne podejście do życia",
  "Kocham Cię za to, że zawsze masz dla mnie czas",
  "Kocham Cię za Twoje pasje",
  "Kocham Cię za Twój entuzjazm do nowych pomysłów",
  "Kocham Cię za Twoje niezależność i siłę charakteru",
  "Kocham Cię za Twoją delikatność",
  "Kocham Cię za to, że potrafisz podnieść mnie na duchu",
  "Kocham Cię za to, jak dbasz o nasze wspólne chwile",
  "Kocham Cię za to, że zawsze jesteś sobą",
  "Kocham Cię za to, że nigdy nie zmuszasz mnie do niczego",
  "Kocham Cię za to, że potrafisz być wyrozumiała",
  "Kocham Cię za Twoją lojalność",
  "Kocham Cię za Twój bezinteresowny charakter",
  "Kocham Cię za Twoją determinację w dążeniu do celu",
  "Kocham Cię za Twoje bezwarunkowe wsparcie",
  "Kocham Cię za to, że przy Tobie czuję się kochany",
  "Kocham Cię za to, jak doceniasz drobne gesty",
  "Kocham Cię za to, jak dbasz o naszą relację",
  "Kocham Cię za Twoje spontaniczne pomysły",
  "Kocham Cię za to, jak potrafisz wprowadzać radość do mojego życia",
  "Kocham Cię za to, jak bardzo potrafisz się poświęcić",
  "Kocham Cię za Twoje poczucie estetyki",
  "Kocham Cię za to, że zawsze potrafisz znaleźć rozwiązanie problemu",
  "Kocham Cię za to, że zawsze sprawiasz, że czuję się dobrze",
  "Kocham Cię za Twoje pozytywne nastawienie",
  "Kocham Cię za Twoje ciepło i opiekuńczość",
  "Kocham Cię za Twoje umiejętności organizacyjne",
  "Kocham Cię za Twoją gotowość do pomocy",
  "Kocham Cię za Twoje przywiązanie do tradycji",
  "Kocham Cię za to, że potrafisz być romantyczna",
  "Kocham Cię za to, że zawsze mogę na Ciebie liczyć",
  "Kocham Cię za to, że kochasz siebie",
  "Kocham Cię za Twoje zaangażowanie",
  "Kocham Cię za Twoje piękne gesty miłości",
  "Kocham Cię za Twoje oddanie",
  "Kocham Cię za to, że potrafisz wybaczać",
  "Kocham Cię za Twoje wsparcie w każdej sytuacji",
  "Kocham Cię za Twoją łagodność",
  "Kocham Cię za Twoje poczucie sprawiedliwości",
  "Kocham Cię za Twoje umiejętności słuchania",
  "Kocham Cię za to, że potrafisz być szczera",
  "Kocham Cię za Twoje wielkie serce",
  "Kocham Cię za Twoją wyjątkowość",
  "Kocham Cię za Twoje zaangażowanie w naszą przyszłość",
  "Kocham Cię za to, że czuję się z Tobą spełniony",
  "Kocham Cię za Twoje pozytywne podejście do życia",
  "Kocham Cię za to, że motywujesz mnie do bycia lepszym człowiekiem",
  "Kocham Cię za Twoje zdolności przywódcze",
  "Kocham Cię za Twoje umiejętności rozwiązywania konfliktów",
  "Kocham Cię za Twoje wspólne plany na przyszłość",
  "Kocham Cię za Twoją empatię",
  "Kocham Cię za Twoją gotowość do kompromisów",
  "Kocham Cię za Twoje poczucie odpowiedzialności",
  "Kocham Cię za Twoją skromność",
  "Kocham Cię za to, że zawsze potrafisz mnie zaskoczyć",
  "Kocham Cię za Twoje poczucie równowagi w życiu",
  "Kocham Cię za Twoje wytrwałość",
  "Kocham Cię za to, jak pięknie się uśmiechasz",
  "Kocham Cię za Twoje unikalne podejście do życia",
  "Kocham Cię za to, że przy Tobie jestem lepszym człowiekiem",
  "Kocham Cię za Twoje wsparcie w trudnych chwilach",
  "Kocham Cię za Twoje wyrozumiałe serce",
  "Kocham Cię za Twoją pewność siebie",
  "Kocham Cię za to, jak jesteś opiekuńcza",
  "Kocham Cię za Twoją spontaniczność",
  "Kocham Cię za to, że każda chwila z Tobą jest wyjątkowa",
  "Kocham Cię za Twoje ambicje",
  "Kocham Cię za Twoje dążenie do perfekcji",
  "Kocham Cię za Twoje zaangażowanie w naszą miłość",
  "Kocham Cię za Twoje pozytywne nastawienie do życia",
  "Kocham Cię za to, że z Tobą czuję się w pełni sobą",
  "Kocham Cię za Twoje niezachwiane zasady",
  "Kocham Cię za to, że potrafisz być ciepła w każdej sytuacji",
  "Kocham Cię za Twoją umiejętność rozwiązywania problemów",
  "Kocham Cię za Twoje poczucie humoru, które zawsze poprawia mi nastrój",
  "Kocham Cię za Twoje podejście do życia",
  "Kocham Cię za Twoje pasje, które mnie inspirują",
  "Kocham Cię za Twoją gotowość do poświęceń",
  "Kocham Cię za Twoją niepowtarzalność",
  "Kocham Cię za to, jak pięknie dbasz o nasze wspólne chwile",
  "Kocham Cię za Twoją intuicję",
  "Kocham Cię za Twoje umiejętności wychodzenia z trudnych sytuacji",
  "Kocham Cię za to, że potrafisz wznieść się ponad problemami",
  "Kocham Cię za Twoje wspaniałe poczucie własnej wartości",
  "Kocham Cię za Twoją czułość i miłość",
  "Kocham Cię za Twoje oddanie w naszą relację",
  "Kocham Cię za Twoją siłę w dążeniu do celów",
  "Kocham Cię za Twoją opanowanie w stresujących chwilach",
  "Kocham Cię za Twoje zdolności rozwiązywania problemów",
  "Kocham Cię za Twoją szczerą miłość",
  "Kocham Cię za to, że zawsze wiem, że mogę na Ciebie liczyć",
  "Kocham Cię za Twoje wspaniałe serce",
  "Kocham Cię za Twoje oddanie",
  "Kocham Cię za Twoje piękne gesty",
  "Kocham Cię za to, że czuję się przy Tobie wyjątkowo",
  "Kocham Cię za Twoją wielką siłę wewnętrzną",
  "Kocham Cię za Twoją umiejętność przetrwania trudnych chwil",
  "Kocham Cię za Twoją mądrość życiową",
  "Kocham Cię za Twoje podejście do wyzwań",
  "Kocham Cię za Twoją szczerość i otwartość",
  "Kocham Cię za to, jak potrafisz motywować mnie do działania",
  "Kocham Cię za Twoje uczucie bezpieczeństwa, które mi dajesz",
  "Kocham Cię za Twoje zrozumienie w trudnych chwilach",
  "Kocham Cię za to, że zawsze jesteś gotowa do pomocy",
  "Kocham Cię za Twoje podejście do rodziny",
  "Kocham Cię za Twoje marzenia, które podzielasz ze mną",
  "Kocham Cię za Twoją lojalność wobec nas",
  "Kocham Cię za to, że dbasz o naszą przyszłość",
  "Kocham Cię za Twoją wspaniałą empatię",
  "Kocham Cię za Twoje delikatne podejście do innych",
  "Kocham Cię za Twoją gotowość do pracy nad sobą",
  "Kocham Cię za Twoją fantazję i kreatywność",
  "Kocham Cię za Twoje poczucie odpowiedzialności",
  "Kocham Cię za Twoje poświęcenie dla nas",
  "Kocham Cię za to, jak bardzo potrafisz mnie uszczęśliwić",
  "Kocham Cię za Twoje ciepło, które roztaczasz wokół siebie",
  "Kocham Cię za Twoje umiejętności komunikacyjne",
  "Kocham Cię za Twoje umiejętności zarządzania czasem",
  "Kocham Cię za Twoje dążenie do doskonałości",
  "Kocham Cię za Twoją wewnętrzną harmonię",
  "Kocham Cię za Twoją gotowość do kompromisów",
  "Kocham Cię za Twoje silne poczucie wartości",
  "Kocham Cię za Twoje umiejętności radzenia sobie w trudnych sytuacjach",
  "Kocham Cię za Twoje poczucie estetyki",
  "Kocham Cię za Twoje gesty, które pokazują, jak bardzo Ci zależy",
  "Kocham Cię za Twoje umiejętności podejmowania trudnych decyzji",
  "Kocham Cię za to, że zawsze szukasz rozwiązań, a nie problemów",
  "Kocham Cię za Twoje wsparcie, kiedy przeżywam trudne chwile",
  "Kocham Cię za Twoje zaangażowanie w każdy nasz wspólny projekt",
  "Kocham Cię za Twoje zainteresowanie moimi pasjami",
  "Kocham Cię za Twoją radość życia, którą mi przekazujesz",
  "Kocham Cię za Twoje wspólne marzenia",
  "Kocham Cię za Twoją opiekuńczość",
  "Kocham Cię za Twoją zdolność do adaptacji w trudnych sytuacjach",
  "Kocham Cię za Twoje umiejętności wyrażania emocji",
  "Kocham Cię za to, że jesteś moim partnerem w każdej sytuacji",
  "Kocham Cię za Twoje niezłomne zasady",
  "Kocham Cię za Twoje wyrozumienie i cierpliwość",
  "Kocham Cię za to, jak pięknie opowiadasz o swoich marzeniach",
  "Kocham Cię za Twoją lojalność i oddanie",
  "Kocham Cię za Twoje magiczne podejście do życia",
  "Kocham Cię za to, jak często przypominasz mi, że jestem kochany",
  "Kocham Cię za Twoje poczucie równowagi",
  "Kocham Cię za Twoje wysiłki, które wkładasz w naszą relację",
  "Kocham Cię za to, że potrafisz być wsparciem w chwilach kryzysowych",
  "Kocham Cię za Twoją pomysłowość w rozwiązywaniu problemów",
  "Kocham Cię za Twoje wyczucie sytuacji",
  "Kocham Cię za Twoje wewnętrzne piękno",
  "Kocham Cię za to, że zawsze potrafisz mnie wesprzeć",
  "Kocham Cię za Twoje piękne oczy, które są pełne miłości",
  "Kocham Cię za to, że nigdy nie jesteś obojętna na moje potrzeby",
  "Kocham Cię za Twoje ciepło, które roztaczasz wokół siebie",
  "Kocham Cię za Twoje wsparcie, które nigdy nie kończy się słowami",
  "Kocham Cię za to, że potrafisz wyciągać mnie z najgorszych chwil",
  "Kocham Cię za Twoją umiejętność bycia prawdziwym",
  "Kocham Cię za Twoje poczucie sprawiedliwości i równości",
  "Kocham Cię za Twoją chęć pomagania innym",
  "Kocham Cię za Twoje zdolności artystyczne",
  "Kocham Cię za to, że jesteś moim nauczycielem w wielu kwestiach",
  "Kocham Cię za Twoje nieoczywiste, ale szczere podejście do życia",
  "Kocham Cię za to, że zawsze widzisz szklankę do połowy pełną",
  "Kocham Cię za Twoje zrozumienie w chwilach ciszy",
  "Kocham Cię za Twoją wierność w każdych warunkach",
  "Kocham Cię za Twoje uważność na szczegóły",
  "Kocham Cię za to, że sprawiasz, że każdy dzień staje się lepszy",
  "Kocham Cię za Twoje wyjątkowe poczucie humoru",
  "Kocham Cię za Twoje wyjątkowe podejście do wychowania",
  "Kocham Cię za Twoją gotowość do wyciągania mnie z rutyny",
  "Kocham Cię za to, że czuję się przy Tobie kochany każdego dnia",
  "Kocham Cię za to, jak pięknie potrafisz się uśmiechać",
  "Kocham Cię za Twoją otwartość na innych ludzi",
  "Kocham Cię za Twoje piękne gesty czułości",
  "Kocham Cię za to, że razem z Tobą czuję się kompletny",
  "Kocham Cię za Twoją umiejętność bycia obecnym",
  "Kocham Cię za Twoje zdolności przywódcze",
  "Kocham Cię za Twoją silną wolę",
  "Kocham Cię za Twoje delikatne podejście do życia",
  "Kocham Cię za Twoje umiejętności rozwiązywania konfliktów",
  "Kocham Cię za Twoją troskę o detale",
  "Kocham Cię za Twoją chęć do nauki nowych rzeczy",
  "Kocham Cię za Twoje wsparcie w codziennych sprawach",
  "Kocham Cię za Twoją zdolność dostrzegania piękna w drobnych rzeczach",
  "Kocham Cię za Twoje pozytywne nastawienie do problemów",
  "Kocham Cię za Twoje poczucie wewnętrznej harmonii",
  "Kocham Cię za Twoje ciepłe i bezpieczne ramiona",
  "Kocham Cię za Twoją nieocenioną pomoc",
  "Kocham Cię za Twoje zrozumienie w moich chwilach słabości",
  "Kocham Cię za Twoje codzienne starania",
  "Kocham Cię za Twoje serce pełne miłości",
  "Kocham Cię za Twoje wrażliwość na innych ludzi",
  "Kocham Cię za Twoją niezależność",
  "Kocham Cię za to, że zawsze dążysz do rozwoju",
  "Kocham Cię za Twoje umiejętności motywowania mnie",
  "Kocham Cię za Twoje otwarte serce",
  "Kocham Cię za Twoje wsparcie we wszystkich trudnych momentach",
  "Kocham Cię za Twoje ciągłe dążenie do lepszej wersji siebie",
  "Kocham Cię za Twoje umiejętności przekonywania",
  "Kocham Cię za Twoje subtelne gesty miłości",
  "Kocham Cię za Twoje poświęcenie w trudnych czasach",
  "Kocham Cię za Twoje poczucie odpowiedzialności za naszą przyszłość",
  "Kocham Cię za Twoje umiejętności wybaczania",
  "Kocham Cię za Twoje wyjątkowe umiejętności planowania",
  "Kocham Cię za Twoje zaangażowanie w naszą relację",
  "Kocham Cię za to, że potrafisz dawać przestrzeń, ale i być blisko",
  "Kocham Cię za Twoje nieustanne starania, aby poprawić nasze życie",
  "Kocham Cię za to, że razem z Tobą czuję, że życie ma sens",
  "Kocham Cię za Twoje niezmienne poczucie humoru",
  "Kocham Cię za to, że jesteś moją ostoją",
  "Kocham Cię za Twoją wewnętrzną siłę",
  "Kocham Cię za Twoje śmiechy, które są lepsze niż jakiekolwiek słowa",
  "Kocham Cię za Twoją czułość i zrozumienie w najtrudniejszych chwilach",
  "Kocham Cię za Twoje podejście do problemów",
  "Kocham Cię za Twoje bezwarunkowe wsparcie w każdej sytuacji",
  "Kocham Cię za Twoje ogromne serce",
  "Kocham Cię za to, jak motywujesz mnie do bycia lepszym człowiekiem",
  "Kocham Cię za to, że nigdy się nie poddajesz",
  "Kocham Cię za to, jak sprawiasz, że czuję się najważniejszy",
  "Kocham Cię za Twoją wrażliwość na potrzeby innych",
  "Kocham Cię za to, że nigdy nie zmuszasz mnie do niczego",
  "Kocham Cię za Twoje wspaniałe podejście do przyjaciół i rodziny",
  "Kocham Cię za Twoje nieustanne dążenie do rozwoju osobistego",
  "Kocham Cię za Twoje serdeczność wobec innych",
  "Kocham Cię za Twoje umiejętności słuchania",
  "Kocham Cię za Twoją wewnętrzną harmonię, którą przekazujesz wszystkim wokół",
  "Kocham Cię za Twoje silne poczucie sprawiedliwości",
  "Kocham Cię za Twoje poświęcenie dla naszej relacji",
  "Kocham Cię za Twoje spokojne podejście do trudnych sytuacji",
  "Kocham Cię za to, jak potrafisz mnie zaskakiwać swoimi pomysłami",
  "Kocham Cię za to, że zawsze wiesz, jak poprawić mi humor",
  "Kocham Cię za Twoje niezawodne poczucie bezpieczeństwa, które mi dajesz",
  "Kocham Cię za Twoje dążenie do zrozumienia innych",
  "Kocham Cię za Twoją gotowość do zmiany, jeśli coś nie działa",
  "Kocham Cię za Twoje ogromne serce, które ma miejsce dla każdego",
  "Kocham Cię za to, że nigdy nie pozwalasz mi się poddać",
  "Kocham Cię za Twoje czułe słowa, które nigdy nie tracą na sile",
  "Kocham Cię za to, że wiesz, kiedy milczeć, a kiedy mówić",
  "Kocham Cię za to, że potrafisz wybaczyć, nawet w trudnych sytuacjach",
  "Kocham Cię za Twoje umiejętności rozwiązywania problemów",
  "Kocham Cię za Twoje otwarte serce i umysł",
  "Kocham Cię za Twoje poczucie stabilności, które mi dajesz",
  "Kocham Cię za Twoje dbanie o naszą przyszłość",
  "Kocham Cię za to, jak starasz się codziennie być lepszą osobą",
  "Kocham Cię za Twoją chęć do kompromisów, kiedy jest to konieczne",
  "Kocham Cię za Twoje poczucie humoru, które nie zna granic",
  "Kocham Cię za Twoje silne ramiona, na które mogę liczyć",
  "Kocham Cię za to, że potrafisz dostrzegać moje potrzeby, zanim ja je wyrażę",
  "Kocham Cię za Twoje poczucie winy, kiedy coś zawalam, nawet jeśli to nie jest Twoja wina",
  "Kocham Cię za Twoje oddanie dla naszej relacji",
  "Kocham Cię za Twoje bezinteresowne wsparcie",
  "Kocham Cię za Twoje poświęcenie dla moich pasji",
  "Kocham Cię za Twoje zdolności do adaptacji w każdej sytuacji",
  "Kocham Cię za Twoją szlachetność i dobroć",
  "Kocham Cię za Twoją umiejętność przekonywania do swoich racji w sposób delikatny",
  "Kocham Cię za Twoje bezgraniczne zaufanie do mnie",
  "Kocham Cię za Twoją gotowość do poświęceń, gdy tego potrzebuję",
  "Kocham Cię za Twoje zmysłowe podejście do miłości",
  "Kocham Cię za Twoje zdecydowanie w trudnych sytuacjach",
  "Kocham Cię za Twoje zaangażowanie w każdą część naszego wspólnego życia",
  "Kocham Cię za Twoje cierpliwe wyjaśnianie rzeczy, których nie rozumiem",
  "Kocham Cię za Twoje zdolności organizacyjne, które sprawiają, że nasze życie jest płynne",
  "Kocham Cię za Twoje umiejętności tworzenia wspaniałych wspomnień",
  "Kocham Cię za Twoje codzienne troski i zainteresowanie",
  "Kocham Cię za Twoje poświęcenie dla wspólnego celu",
  "Kocham Cię za Twoje serdeczne gesty, które zawsze robią dzień lepszym",
  "Kocham Cię za Twoje umiejętności rozwiązywania konfliktów bez straty miłości",
  "Kocham Cię za Twoje głębokie myślenie, które pomaga mi patrzeć na świat z innej perspektywy",
  "Kocham Cię za Twoją gotowość do naprawy swoich błędów",
  "Kocham Cię za Twoje umiejętności wyciągania wniosków z przeszłości",
  "Kocham Cię za Twoje uczucie odpowiedzialności za naszą przyszłość",
  "Kocham Cię za Twoją opiekuńczość, która sprawia, że czuję się kochany",
  "Kocham Cię za Twoją zmysłowość i subtelne gesty",
  "Kocham Cię za Twoje wyrozumienie i empatię w każdym aspekcie życia",
  "Kocham Cię za Twoje nieustanne dążenie do harmonii w relacjach",
  "Kocham Cię za Twoje szczere zainteresowanie moimi uczuciami",
  "Kocham Cię za Twoje umiejętności dostosowania się do różnych sytuacji",
  "Kocham Cię za Twoje poczucie przygody, które daje naszemu życiu radość",
  "Kocham Cię za to, że zawsze widzisz najlepsze w ludziach",
  "Kocham Cię za Twoją cierpliwość w nauce nowych rzeczy",
  "Kocham Cię za Twoje niezachwiane przekonanie, że razem możemy wszystko",
  "Kocham Cię za Twoje spokojne podejście do życia, które mnie uspokaja",
  "Kocham Cię za Twoje entuzjastyczne podejście do nowych wyzwań",
  "Kocham Cię za Twoje docenianie każdej chwili spędzonej razem",
  "Kocham Cię za Twoje nieoczywiste piękno, które dostrzegam w każdym Twoim geście",
  "Kocham Cię za Twoją miłość do życia, która mnie inspiruje",
  "Kocham Cię za Twoje serce, które jest moim domem",
  "Kocham Cię za to, jak potrafisz zrobić każdy dzień lepszym",
  "Kocham Cię za Twoje poczucie humoru, które sprawia, że życie jest lżejsze",
  "Kocham Cię za Twoje dążenie do doskonałości, które mnie inspiruje",
  "Kocham Cię za Twoje ciepło, które czuję nawet w chłodne dni",
  "Kocham Cię za Twoje umiejętności przepraszania, gdy coś jest nie tak",
  "Kocham Cię za Twoją nieskończoną kreatywność",
  "Kocham Cię za Twoje zaangażowanie w nasze wspólne cele",
  "Kocham Cię za Twoje umiejętności wychodzenia ze stresujących sytuacji z uśmiechem",
  "Kocham Cię za Twoje poczucie wdzięczności, które pokazujesz codziennie",
  "Kocham Cię za to, że potrafisz widzieć dobro w innych",
  "Kocham Cię za Twoje wzruszające gesty, które wyrażają więcej niż słowa",
  "Kocham Cię za Twoją zdolność do wybaczania i zapominania",
  "Kocham Cię za to, że potrafisz stać obok mnie nawet w trudnych chwilach",
  "Kocham Cię za Twoje silne poczucie odpowiedzialności",
  "Kocham Cię za Twoje otwarte serce, które daje poczucie bezpieczeństwa",
  "Kocham Cię za Twoje umiejętności organizacyjne, które sprawiają, że wszystko jest uporządkowane",
  "Kocham Cię za Twoje niezachwiane wsparcie, które zawsze czuję",
  "Kocham Cię za Twoje umiejętności radzenia sobie z przeciwnościami",
  "Kocham Cię za Twoje bezwarunkowe wsparcie w moich pasjach",
  "Kocham Cię za Twoje unikalne spojrzenie na świat, które mnie wzbogaca",
  "Kocham Cię za Twoje poczucie współczucia dla innych",
  "Kocham Cię za Twoją cierpliwość, która pozwala mi się rozwijać",
  "Kocham Cię za Twoją wytrwałość w dążeniu do celów",
  "Kocham Cię za Twoje oddanie naszemu wspólnemu życiu",
  "Kocham Cię za Twoje zachwycające talenty, które często skromnie ukrywasz",
  "Kocham Cię za Twoje umiejętności w rozwiązywaniu konfliktów",
  "Kocham Cię za Twoje pozytywne podejście do życia, które sprawia, że czuję się lepiej",
  "Kocham Cię za Twoją nieustanną troskę o mnie",
  "Kocham Cię za to, że potrafisz sprawić, by każdy dzień był niezapomniany",
  "Kocham Cię za Twoje nieskończone zapasy energii i entuzjazmu",
  "Kocham Cię za Twoją otwartość na nowe wyzwania",
  "Kocham Cię za Twoje oddanie dla naszej wspólnej przyszłości",
  "Kocham Cię za to, jak umiesz mnie pocieszyć, gdy tego najbardziej potrzebuję",
  "Kocham Cię za Twoje cierpliwe słuchanie, które pomaga mi się wyładować",
  "Kocham Cię za Twoje zrozumienie i szacunek dla moich pasji",
  "Kocham Cię za Twoje poczucie humoru, które zawsze poprawia mi nastrój",
  "Kocham Cię za to, jak potrafisz wyciągać mnie z moich własnych trudnych sytuacji",
  "Kocham Cię za Twoje wsparcie w moich marzeniach",
  "Kocham Cię za Twoje umiejętności zarządzania czasem, które sprawiają, że wszystko jest na swoim miejscu",
  "Kocham Cię za Twoje bezinteresowne oddanie się naszej relacji",
  "Kocham Cię za Twoje niezawodne poczucie humoru, które wyciąga mnie z najgorszych dni",
  "Kocham Cię za Twoje zrozumienie, które nigdy nie zawodzi",
  "Kocham Cię za Twoje oddanie rodzinie i bliskim",
  "Kocham Cię za Twoje talenty, które zawsze mnie zachwycają",
  "Kocham Cię za Twoje idealne połączenie delikatności i siły",
  "Kocham Cię za Twoją cierpliwość, gdy uczę się czegoś nowego",
  "Kocham Cię za Twoje wspólne spędzanie czasu, które nigdy nie jest nudne",
  "Kocham Cię za Twoje wsparcie w najtrudniejszych momentach",
  "Kocham Cię za Twoje zdolności motywowania mnie do działania",
  "Kocham Cię za Twoje poczucie bezpieczeństwa, które daje mi spokój",
  "Kocham Cię tak po prostu <333",
  "Kocham Cię za to, że jesteś",
  "Kocham Cię za to, że będziesz zawsze",
  "Kocham Cię za to, że tak na mnie działasz",
  "Kocham Cię za to, że rozumiesz mnie bez słów",
  "Kocham Cię za to, że potrafisz mnie znieść",
  "Kocham Cię za to, że stale mnie tolerujesz hihi",
  "Kocham Cię za te wszystkie czułe słowa które do mnie mówisz",
  "Kocham Cię za to, że potrafisz odpuścić a nie stale stawiasz na swoim",
  "Kocham Cię za drapu drapu po pleckach hihi",
];

// Spadające serca
setInterval(() => {
  const heart = document.createElement('div');
  heart.classList.add('heart');
  heart.style.left = Math.random() * 100 + 'vw';
  heart.style.animationDuration = (3 + Math.random() * 2) + 's';
  document.body.appendChild(heart);

  setTimeout(() => {
    heart.remove();
  }, 5000);
}, 300);

document.getElementById('heartButton').addEventListener('click', () => {
  const today = new Date();
  const start = new Date(today.getFullYear(), 0, 0);
  const diff = today - start;
  const day = Math.floor(diff / (1000 * 60 * 60 * 24));
  const reason = reasons[day % reasons.length];

  document.getElementById('heartButton').style.display = 'none';
  const reasonEl = document.getElementById('reason');
  reasonEl.textContent = reason || "Po prostu kocham Cię za wszystko ❤️";
  reasonEl.classList.remove('hidden');
  reasonEl.classList.add('show');
});
function typeWriter(text, element, speed = 50) {
  element.textContent = '';
  let i = 0;
  const interval = setInterval(() => {
    element.textContent += text.charAt(i);
    i++;
    if (i >= text.length) clearInterval(interval);
  }, speed);
}

document.getElementById('heartButton').addEventListener('click', () => {
  const today = new Date();
  const start = new Date(today.getFullYear(), 0, 0);
  const diff = today - start;
  const day = Math.floor(diff / (1000 * 60 * 60 * 24));
  const reasonText = reasons[day % reasons.length] || "Po prostu kocham Cię za wszystko ❤️";

  const reasonEl = document.getElementById('reason');
  document.getElementById('heartButton').style.display = 'none';
  reasonEl.classList.remove('hidden');
  reasonEl.classList.add('show');

  typeWriter(reasonText, reasonEl);
});